// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf0pwDPe6UR7mIsFFrwI96cg_yFvYx2Aw',
    appId: '1:650200152419:web:c280e8f66d519585073b56',
    messagingSenderId: '650200152419',
    projectId: 'valutnest',
    authDomain: 'valutnest.firebaseapp.com',
    storageBucket: 'valutnest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfWr-y0EgHZ5XnRzEVnmZAU6rm_BjYbwg',
    appId: '1:650200152419:android:01924494be3e0e1c073b56',
    messagingSenderId: '650200152419',
    projectId: 'valutnest',
    storageBucket: 'valutnest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFQW_GjLDVSe-EkuidsnTr2CsTnbFoRto',
    appId: '1:650200152419:ios:425f645ba17075da073b56',
    messagingSenderId: '650200152419',
    projectId: 'valutnest',
    storageBucket: 'valutnest.appspot.com',
    iosBundleId: 'com.example.passlock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFQW_GjLDVSe-EkuidsnTr2CsTnbFoRto',
    appId: '1:650200152419:ios:425f645ba17075da073b56',
    messagingSenderId: '650200152419',
    projectId: 'valutnest',
    storageBucket: 'valutnest.appspot.com',
    iosBundleId: 'com.example.passlock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf0pwDPe6UR7mIsFFrwI96cg_yFvYx2Aw',
    appId: '1:650200152419:web:a02eca71dae778a0073b56',
    messagingSenderId: '650200152419',
    projectId: 'valutnest',
    authDomain: 'valutnest.firebaseapp.com',
    storageBucket: 'valutnest.appspot.com',
  );

}